
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: impati
    password: impati
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: true
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3.decoupled-logic: true


management:
  endpoints:
    web:
      exposure:
        include: "*"


debug: false

logging:
  level:
    com.example.normalboard : debug
    org.springframework.web.servlet : debug

---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
#  test.database.replace: none

